spring:
  cloud:
    stream:
      sqs:
        bindings:
          user-input-0:
            consumer:
              snsFanout: false
          email-input-0:
            consumer:
              snsFanout: false
          article-input-0:
            consumer:
              snsFanout: false
          comment-input-0:
            consumer:
              snsFanout: false
      bindings:
        user-out-0:
          destination: user
        user-input-0:
          destination: user
        email-out-0:
          destination: email
        email-input-0:
          destination: email
        article-out-0:
          destination: article
        article-input-0:
          destination: article
        comment-out-0:
          destination: comment
        comment-input-0:
          destination: comment
      function:
        bindings:
          user-in-0: user-input-0
          email-in-0: email-input-0
          article-in-0: article-input-0
          comment-in-0: comment-input-0
        definition: user;email;article;comment
cloud:
  aws:
    region:
      static: "eu-central-1"
    stack:
      auto: false
    credentials:
      access-key: "mock_access_key"
      secret-key: "mock_secret_key"
    sqs:
      endpoint: "http://127.0.0.1:4566"
