
spring:
  cloud:
    function:
      definition: user;email;comment;article;logger
    stream:
      bindings:
        user-in-0:
          destination: user-created
        email-in-0:
          destination: email-sent
        comment-in-0:
          destination: "comment-created,comment-deleted,comment-updated"
        article-in-0:
          destination: "article-created,article-updated"
        logger-in-0:
          destination: "comment-created,comment-deleted,comment-updated,user-created,email-sent,article-created,article-updated"
      kafka:
        default:
          producer:
            useTopicHeader: true