spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: user;topicLogger;article;comment;email
    stream:
      bindings:
        user-out-0:
          destination: user-out
        user-in-0:
          destination: user-out
          group: "userAllEvents"
        article-out-0:
          destination: article-out
        article-in-0:
          destination: article-out
          group: "articleAllEvents"
        comment-out-0:
          destination: comment-out
        comment-in-0:
          destination: comment-out
          group: "commentAllEvents"
        email-out-0:
          destination: email-out
        email-in-0:
          destination: email-out
          group: "emailToUser"
        topicLogger-in-0:
          destination: "user-out,comment-out,article-out"
          group: "topicLogger"
      rabbit:
        bindings:
          user-out-0:
            producer:
              routing-key-expression: headers.routing_key
          article-out-0:
            producer:
              routing-key-expression: headers.routing_key
          comment-out-0:
            producer:
              routing-key-expression: headers.routing_key
          email-out-0:
            producer:
              routing-key-expression: headers.routing_key
              exchange-type: direct
          user-in-0:
            consumer:
              binding-routing-key: "user.#"
              queue-name-group-only: true
              durable-subscription: false
          article-in-0:
            consumer:
              binding-routing-key: "article.#"
              queue-name-group-only: true
              durable-subscription: false
          comment-in-0:
            consumer:
              binding-routing-key: "comment.#"
              queue-name-group-only: true
              durable-subscription: false
          email-in-0:
            consumer:
              binding-routing-key: "email"
              queue-name-group-only: true
              durable-subscription: false
              exchange-type: direct
          topicLogger-in-0:
            consumer:
              binding-routing-key: "#"
              queue-name-group-only: true
              durable-subscription: false

